nebula-logger/main/mappings/objects/LogEntryEventMapping__mdt/LogEntryEventMapping__mdt.object-meta.xml
<CustomObject>
    <label>Log Entry Event Mapping</label>
    <pluralLabel>Log Entry Event Mappings</pluralLabel>
</CustomObject>

nebula-logger/main/mappings/objects/LogEntryEventMapping__mdt/fields/LogEntryEventField__c.field-meta.xml
<CustomField>
    <fullName>LogEntryEventField__c</fullName>
    <label>Log Entry Event Field</label>
    <metadataRelationshipControllingField>LogEntryEventMapping__mdt.LogEntryEventSObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Log_Entry_Event_Mappings</relationshipLabel>
    <relationshipName>Log_Entry_Event_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

nebula-logger/main/mappings/objects/LogEntryEventMapping__mdt/fields/LogEntryEventSObject__c.field-meta.xml
<CustomField>
    <fullName>LogEntryEventSObject__c</fullName>
    <label>Log Entry Event Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Log_Entry_Event_Mappings</relationshipLabel>
    <relationshipName>Log_Entry_Event_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

nebula-logger/main/mappings/objects/LogEntryEventMapping__mdt/fields/MappedField__c.field-meta.xml
<CustomField>
    <fullName>MappedField__c</fullName>
    <label>Mapped Field</label>
    <metadataRelationshipControllingField>LogEntryEventMapping__mdt.MappedSObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Log_Entry_Event_Mappings1</relationshipLabel>
    <relationshipName>Log_Entry_Event_Mappings1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

nebula-logger/main/mappings/objects/LogEntryEventMapping__mdt/fields/MappedSObject__c.field-meta.xml
<CustomField>
    <fullName>MappedSObject__c</fullName>
    <label>Mapped Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Log_Entry_Event_Mappings1</relationshipLabel>
    <relationshipName>Log_Entry_Event_Mappings1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

nebula-logger/main/mappings/classes/LogEntryEventMapper.cls
public with sharing class LogEntryEventMapper {
    public static void mapFields(LogEntryEvent__e logEntryEvent, SObject mappedRecord) {
        List<LogEntryEventMapping__mdt> mappedRecordMappings = getMappings(mappedRecord.getSObjectType());

        for (LogEntryEventMapping__mdt mapping : mappedRecordMappings) {
            String logEntryEventField = mapping.LogEntryEventField__r.QualifiedApiName;
            String mappedRecordField = mapping.MappedField__r.QualifiedApiName;
            Object logEntryEventValue = logEntryEvent.get(logEntryEventField);

            mappedRecord.put(mappedRecordField, logEntryEventValue);
        }
    }

    private static List<LogEntryEventMapping__mdt> getMappings(Schema.SObjectType mappedSObjectType) {
        return [
            SELECT
                LogEntryEventSObject__r.QualifiedApiName,
                LogEntryEventField__r.QualifiedApiName,
                MappedSObject__r.QualifiedApiName,
                MappedField__r.QualifiedApiName
            FROM logEntryEventMapping__mdt
            WHERE MappedSObject__r.QualifiedApiName = :mappedSObjectType
        ];
    }
}